[package]
name = "constructor-macro"
version = "0.1.0"
authors = ["Kai <thiskaiguy@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "0.4.27"
quote = "0.6.11"
proc-macro-crate = "0.1.3"

[dependencies.syn]
version = "0.15.29"
features = [
    "full",
]
