[package]
name = "constructor-macro"
version = "0.1.0"
authors = ["Kai <thiskaiguy@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
quote = "0.6.11"

[dependencies.syn]
version = "0.15.29"
features = [
    "full",
]
